main: me.sonny.SQLiteLib.SQLiteLib
name: SQLiteLib
version: 0.2.0
description: SQLiteLib provides an easy way to access SQLite.
author: Sonny Kim

commands:
  sqlite:
    description: SQLite commands.
    
permissions:
  sqlite.use:
    description: Use sqlite command.
    default: op